<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Condition="'$(Configuration)' == ''">
		<Configuration>R2026</Configuration>
	</PropertyGroup>
	<PropertyGroup>
		<AssemblyName>AirBalance</AssemblyName>
		<RootNamespace>AirBalance</RootNamespace>
		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)' == 'net48'">
		<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
	</PropertyGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net48'">
		<PackageReference Include="System.Resources.Extensions" Version="8.0.0" IncludeAssets="build;compile" PrivateAssets="all" />
	</ItemGroup>
	<ItemGroup>
		<Resource Include="Resources\citrus.ico" />
	</ItemGroup>
</Project>
